# -------------------
# Jekyll Config
# --------------------
baseurl: ""
url: ""
permalink: pretty
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-environment-variables
  - jekyll-paginate

# Collections
collections_dir: collections
collections:
  work:
    output: true
    permalink: /:collection/:path/
  posts:
    output: true
    permalink: /blog/:path/

# Pages
defaults:
  - scope:
      path: ""
      type: work
    values:
      layout: work
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      weight: 999
  - scope:
      path: "images"
    values:
      image: true
  - scope:
      path: "categories"
    values:
      permalink: /category/:basename/
  - scope:
      path: "pages"
    values:
      permalink: /:basename/

# SCSS
sass:
  style: compact

# Excludes
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - netlify.toml


# -------------------
# Theme Config
# --------------------
title: "Jekyll Lever"
category_dir: category

colors:
  # light
  base_bg: '#ffffff'
  base_bg_2: '#fcfcfc'
  base_bg_3: '#f2f2f2'
  base_text: '#2f2e2a'
  base_text_2: '#535247'
  base_text_3: '#848484'
  primary_bg: '#46e385'
  primary_bg_2: '#55f884'
  primary_bg_3: '#46e385'
  primary_text: '#114c29'
  primary_text_2: '#f9f8ef'
  logo_text: '#202020'
  menu_text: '#202020'
  
  # dark
  base_bg_dark: '#0b0b0b'
  base_bg_2_dark: '#212123'
  base_bg_3_dark: '#7e7e82'
  base_text_dark: '#ffffff'
  base_text_2_dark: '#bfc1c2'
  base_text_3_dark: '#a8a4a4'
  primary_bg_dark: '#46e385'
  primary_bg_2_dark: '#55f884'
  primary_bg_3_dark: '#46e385'
  primary_text_dark: '#114c29'
  primary_text_2_dark: '#f9f8ef'
  logo_text_dark: '#ffffff'
  menu_text_dark: '#ffffff'

fonts:
  use_google_fonts: false
  google_fonts_url: "https://fonts.googleapis.com/css2?family=Inter:wght@100;300;400;600;800&display=swap"
  use_self_hosted_fonts: true # font files must be placed in /assets/fonts folder and the @font-face definitions must be added to /assets/css/fonts.css
  heading: "Inter"
  base: "Inter"
  monospace: "'Fira Mono'"
  logo: "Inter"

logo:
  logo_text: "Sean Kim"
  # logo_image: assets/images/logo/logo.svg
  logo_image_mobile: assets/images/logo/logo-mobile.svg
  logo_image_invert: assets/images/logo/logo-invert.svg
  logo_image_invert_mobile: assets/images/logo/logo-invert-mobile.svg
  logo_image_desktop_height: "18px"
  logo_image_desktop_width: "32px"
  logo_image_mobile_height: "18px"
  logo_image_mobile_width: "32px"
  show_logo_image_on_mobile: true
  show_logo_image_on_desktop: true
  show_logo_text_on_mobile: false
  show_logo_text_on_desktop: true

header: 
  fixed: false

open_graph:
  meta_opengraph_type: "website"
  meta_twitter_card: "summary"
  meta_twitter_site: "@zerostaticio"
  meta_twitter_creator: "@zerostaticio"

darkmode:
  enable_dark_mode: true
  show_dark_mode_toggle_in_header: true
  show_dark_mode_toggle_in_footer: false
  show_dark_mode_toggle_in_bottom: false
  show_dark_mode_toggle_in_mobile_menu: true

cookie_banner:
  enabled: false
  show_manage_cookies_at_bottom: false

analytics:
  google_analytics_id: "" # G-XXXXXXXXXX
  gtm_id: "" # GTM-XXXXXXXX
  plausible_data_domain: "" # example: mywebsite.com
  umami_data_website_id: "" # example: "ddd14336-5fb0-4cdd-8f32-e1bfa906cc2b"
  umami_src: "" # "https://analytics.eu.umami.is/script.js"

comments:
  commento:
    enabled: true # you must have a commento account and be on the correct domain. does not work locally.
  disqus:
    shortname: "" # Your disqus shortcode for example "zerostatic". leave this blank ie "" to disable.

newsletter:
  mailchimp:
    form_action_url: https://zerostatic.us21.list-manage.com/subscribe/post?u=798e19886b83aaab346734382&amp;id=f1c526a772&amp;f_id=0027e3e6f0
    form_title: "Let's keep in touch"

contact_form: 
  use_netlify_form: false
  use_formspree_form: true
  formspree_endpoint: https://formspree.io/f/moqyklqv
  netlify_form_name: "contact"

menu: 
  show_dropdown_items_in_mobile_menu: false
  show_social_media_in_mobile_menu: true

footer:
  enable_footer: false # show/hide the entire footer
  footer_title: "Get In Touch"
  footer_description: ""
  enable_social_media_icons: false
  enable_contact_details: false
  enable_menu_footer_primary: false
  enable_menu_footer_secondary: false
  enable_menu_footer_tertiary: false
  footer_primary_menu_title: "Product"
  footer_secondary_menu_title: "Company"
  footer_tertiary_menu_title: "Legal"

bottom:
  enable_bottom: false # show/hide the entire bottom (below the footer)
  enable_bottom_menu: false # if enabled, the bottom menu can be edited in `_data/menu.yml`
  copyright_text: "© 2021 Zerostatic Themes"
  show_rss_icon: true
